version: "3.8"
services: 
    backend:
        build: 
            context: .
            args:
                user: trannguyenhan
                uid: 1000
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        networks:
            - h3t
    
    nginx:
        image: nginx:stable-alpine
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html/
            - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - h3t

    db:
        image: mysql
        environment:
            MYSQL_DATABASE: traveltours
            MYSQL_ROOT_PASSWORD: mysql12345
            MYSQL_USER: trannguyenhan
            MYSQL_PASSWORD: mysql12345
        ports: 
            - "9906:3306"
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/
        networks:
            - h3t
networks: 
    h3t:
        driver: bridge
