<?php

namespace App\Http\Repositories;

use Illuminate\Http\JsonResponse;

class TourRepository extends BaseRepository
{
    protected $_relationships = ['placeSource', 'placeDest', 'categories', 'placeDest.reviews', 'placeDest.reviews.user'];

    public function getModel()
    {
        return \App\Models\Tour::class;
    }

    public function doUpdate($arr): JsonResponse
    {
        return parent::doUpdate($arr); // TODO: Change the autogenerated stub
    }

    public function doStore($arr): JsonResponse
    {
        return parent::doStore($arr); // TODO: Change the autogenerated stub
    }
}
